### ISSUE TITLE
Domain access failed to load during phase: bootstrap include. Please check your settings.php file and site configuration.

### ISSUE THREAD

**Issue by bdalomgir** [backdrop-contrib/domain#4] opened 2024-02-14 07:20 UTC
We are trying to help with the port of this module and are looking for help solving this problem.

I tried to install the domain module multiple times and each time I found the following error, seems we are stuck over here.

> Domain access failed to load during phase: bootstrap include. Please check your settings.php file and site configuration.

**Steps to reproduce:**
1. Install a fresh Backdrop.
2. Download domain module from - https://github.com/backdrop-contrib/domain
3. added the below line to the settings file
	`include BACKDROP_ROOT . '/modules/domain/settings.inc';`
4. Install only the "Domain Access" module through UI.
5. Got error "Domain access failed to load during phase: bootstrap include. Please check your settings.php file and site configuration."
6. Rebuild permission
7. Added the following line to the settings file
	`$conf['domain_hide_errors'] = TRUE;`

Still, the error persists mentioned in step 5.

Any thoughts or suggestions for how we resolve (debug) this issue and move on to the next?

**Comment by stpaultim** [comment] 2024-02-14 07:31
@bdalomgir Are there any other issues showing up in the Backdrop error log or is this the error that is blocking any progress?

Maybe if there are other errors showing up and we fix them, it will help with the bootstrapping process?

**Comment by bdalomgir** [comment] 2024-02-14 07:39
@stpaultim I did not find any other errors in the Backdrop error logs, it shows only one error I mentioned above without mentioning the file name or line numbers. Please check the screenshot.

![Log-message-Backdrop-Domain](https://github.com/backdrop-contrib/domain/assets/13948360/5efcb91a-e0e6-4736-8a81-bac80e9ae2cc)

**Comment by herbdool** [comment] 2024-02-14 12:42
I don't think `$conf` is a global variable anymore.

**Comment by stpaultim** [comment] 2024-02-14 20:59
@jenlampton Shared this feedback in Zulip.

> I'd remove the line from your settings file (step 3) and try again.
> 
> That's not a safe way to include files anyway, and there may be something
> in that file that's causing issues.
> 
> See if the module will install without whatever's in that file.

**Comment by yorkshire-pudding** [comment] 2024-02-14 21:30
@bdalomgir - I don't have an answer, but a possible clue.
I installed the Object Log module and in file domain.module on line 97, which is just before that error is generated, I added the following line.:
```php
  object_log('domain_init:$_domain', $_domain);
```
Looking in Object Log (`admin/reports/object_log`) I see that this is an empty array so somewhere the list of domains is not being loaded, which is triggering that error.

This module could be helpful, but it will only help once backdrop is bootstrapped; no good in the initialization phases.

I've also spotted some Coder Upgrade relics - search for "dynamic variable" . I don't think any of these are the cause though.

**Comment by stpaultim** [comment] 2024-02-16 09:53
@yorkshire-pudding or @bdalomgir 

How could it have a list of domains before it's been bootstrapped. This needs to be configured later.

**Comment by yorkshire-pudding** [comment] 2024-02-16 09:58
@stpaultim - I'm probably not understanding this but it didn't look like [hook_init()](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_init/1) is called before bootstrap

**Comment by stpaultim** [comment] 2024-02-16 10:04
@jenlampton 

> I'd remove the line from your settings file (step 3) and try again.

That line was not there. The Drupal readme suggests adding that line. We've tried it with and without that line and the results are the same.

**Comment by stpaultim** [comment] 2024-02-16 10:12
@bdalomgir or @sudipto68  I just noticed that despite getting that error, the module is installed and has a menu item for configuration (/admin/structure/domain). When I try to go to that page, I get this error.

`Fatal error: require_once(): Failed opening required '/app/modules/domain-1.x-3.x/domain.admin.inc' (include_path='.:/usr/local/lib/php') in /app/core/modules/system/system.module on line 2619`

Why don't we move on and work on this error and see where it takes us.

![image](https://github.com/backdrop-contrib/domain/assets/3144571/4f9cfca6-3e17-4dff-a103-fab17ee72ac8)

**Comment by yorkshire-pudding** [comment] 2024-02-16 10:16
@stpaultim - just noticed that your module folder does not match the module machine name. I.e. `domain-1.x-3.x` rather than `domain`. That may be the problem here as I think I was able to open the admin page and do some stuff there, albeit with errors.

> `Fatal error: require_once(): Failed opening required '/app/modules/domain-1.x-3.x/domain.admin.inc' (include_path='.:/usr/local/lib/php') in /app/core/modules/system/system.module on line 2619`

**Comment by stpaultim** [comment] 2024-02-16 10:26
@yorkshire-pudding I figured that one out myself and was able to resolve the above error.

![image (10)](https://github.com/backdrop-contrib/domain/assets/3144571/466530b2-33cc-4e34-91a2-a51f1abca9d4)

I'm now this far, but everything I do generates the original error message.

**Comment by yorkshire-pudding** [comment] 2024-02-16 10:28
Yes, same one I'm stuck with.

EDIT: Oops, pressed wrong button, subconscious wishful thinking maybe

**Comment by sudipto68** [comment] 2024-02-20 06:05
@stpaultim @bdalomgir 
I could solve this **Domain access failed to load during phase: bootstrap include** error by changing this following code in the domain.module file on line no #99.
```php
  $_domain = domain_default(TRUE);

  // Error handling in case the module is not installed correctly.
  if (!isset($_domain['domain_id'])) {
    $_domain['error'] = 'bootstrap include';
  }
```

I have just placed the ``` $_domain = domain_default(TRUE); ``` line before the if condition. Because I think, on the first time we have a default domain, so we can set ``` $_domain = domain_default(TRUE)```. If anything goes wrong and it could not find default domain_id then, it can go to the if block.

I have found another issue, this **domain access options** form was not showing on the node add/edit form.
![code2](https://github.com/backdrop-contrib/domain/assets/53519888/d3e503c3-9ffa-4291-8379-a6a6fe061300)

I saw that they were checking, if this is node form then show the domain access options form, on all other form it will return nothing, the code was previously like this(on line number #2946 in domain.module file).

```php
// Apply to all node editing forms only.
  if (empty($form['#node_edit_form'])) {
    return;
  }
```

I have changed the above code to this (But I think only this #node checking is not proper way).

```php
 if (empty($form['#node'])) {
    return;
  }
```
Because I think in backdrop cms there is no #node_edit_form in node add/edit form. After this change the **domain access options** is showing on node add/edit forms. 

I have found another issue after installing this module, if we don't save this configuration then the default domain won't get saved and so that default domain was not showing on the domain list page. A default domain creates but just not show on the domain list page if we don't save this configuration after installing the module. 

![code5](https://github.com/backdrop-contrib/domain/assets/53519888/2022a7ec-5a85-408a-8a27-05d7ba121356)

**Comment by stpaultim** [comment] 2024-02-20 06:51
@sudipto68 - It was my experience last week, that the new domain does not show up on list immediately. But, eventually it did show up.

**Comment by stpaultim** [comment] 2024-02-20 06:52
@sudipto68 - Can you create a Pull Request with the changes you made here?

**Comment by yorkshire-pudding** [comment] 2024-02-20 09:13
@sudipto68 - Thanks for your work on this; I look forward to testing your PR.
Minor point, please can you put code snippets in rather than screenshots of code snippets.

Open with 
` ```php `

and close with

` ``` `
and GitHub does syntax formatting

**Comment by stpaultim** [comment] 2024-02-22 06:40
@sudipto68 and @bdalomgir - I'm going to close this issue for now, because I think the PR we just merged is at least a temporary fix. Let's move on to other issues.

**Closed as completed by stpaultim** 2024-02-22 06:40 UTC
